[package]
name = "study-app"
version = "1.0.1"
authors = ["Lupascu Gabriel Cristian <lupascugabrielcristian@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1"
mysql = "17.0.0"
